# vim: expandtab tabstop=2 shiftwidth=2
name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    name: Build Ghidra FindCrypt extension
    strategy:
      fail-fast: false
      matrix:
        ghidra-version:
          - 'latest'
          - '10.2.3'
          - '10.1.4'
          - '10.1.3'
          - '10.1.2'
          - '10.0.4'
          - '10.0.3'
          - '10.0.2'
          - '10.0.1'
          # Ghidra versions prior to 9.2 lack the Gson JSON library, and are not supported.
    runs-on: ubuntu-latest
    container: ghcr.io/pawlowskialex/ghidra-container:${{ matrix.ghidra-version }}
    steps:
      - name: "Clone FindCrypt"
        uses: actions/checkout@v2
      - name: Compile FindCrypt - ${{ matrix.ghidra-version }}
        run: |
          cd FindCrypt
          gradle
          ls -lah dist/
      - name: Upload FindCrypt - ${{ matrix.ghidra-version }}
        uses: actions/upload-artifact@v2
        with:
          name: ghidra_${{ matrix.ghidra-version }}_FindCrypt
          path: |
            README.md
            FindCrypt/dist/*.zip
          if-no-files-found: error
